#!/bin/sh
#
# @license		http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author       OpenMediaVault Plugin Developers <plugins@omv-extras.org>
# @copyright    Copyright (c) 2014 OpenMediaVault Plugin Developers
#
# This file is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this file. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

FAIL2BAN_CONFIG="/etc/fail2ban/jail.conf"
OMV_FAIL2BAN_PLUGIN_XPATH="//services/fail2ban"

# Generate configuration only if the service is enabled.
if [ "$(omv_config_get "${OMV_FAIL2BAN_PLUGIN_XPATH}/enable")" != "1" ]; then
	exit 0
fi

# Get settings.
ignoreip=$(omv_config_get "${OMV_FAIL2BAN_PLUGIN_XPATH}/ignoreip")
findtime=$(omv_config_get "${OMV_FAIL2BAN_PLUGIN_XPATH}/findtime")
bantime=$(omv_config_get "${OMV_FAIL2BAN_PLUGIN_XPATH}/bantime")
maxretry=$(omv_config_get "${OMV_FAIL2BAN_PLUGIN_XPATH}/maxretry")
destemail=$(omv_config_get "${OMV_FAIL2BAN_PLUGIN_XPATH}/destemail") 
action=$(omv_config_get "${OMV_FAIL2BAN_PLUGIN_XPATH}/action") 

cat <<EOF > ${FAIL2BAN_CONFIG}
# this file was automatically generated

[DEFAULT]

# "ignoreip" can be an IP address, a CIDR mask or a DNS host
ignoreip = ${ignoreip}
findtime = ${findtime}
bantime  = ${bantime}
maxretry = ${maxretry}
backend = auto
destemail = ${destemail}

banaction = iptables-multiport
mta = sendmail
protocol = tcp
chain = INPUT

action_mwl = %(banaction)s[name=%(__name__)s, port="%(port)s", protocol="%(protocol)s", chain="%(chain)s"]
               %(mta)s-whois-lines[name=%(__name__)s, dest="%(destemail)s", logpath=%(logpath)s, chain="%(chain)s"]

action = %(${action})s

[ssh]

enabled  = true
port     = ssh
filter   = sshd
logpath  = /var/log/auth.log
maxretry = 6


EOF

exit 0
