#!/bin/sh
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    OpenMediaVault Plugin Developers <plugins@omv-extras.org>
# @copyright Copyright (c) 2014-2026 openmediavault plugin developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

OMV_AVAILABLE=false
if [ -f /etc/default/openmediavault ] && [ -f /usr/share/openmediavault/scripts/helper-functions ]; then
    . /etc/default/openmediavault
    . /usr/share/openmediavault/scripts/helper-functions
    OMV_AVAILABLE=true
fi

remove_action() {
    if [ "${OMV_AVAILABLE}" = "true" ]; then
        dpkg-trigger update-workbench
    fi
}

delete_config() {
    if [ "${OMV_AVAILABLE}" = "true" ]; then
        omv_config_delete "/config/services/fail2ban"
    elif [ -f /etc/openmediavault/config.xml ] && command -v xmlstarlet >/dev/null 2>&1; then
        xmlstarlet ed -L -d "/config/services/fail2ban" /etc/openmediavault/config.xml || true
    fi
}

case "$1" in
    purge)
        remove_action
        delete_config
    ;;

    remove)
        remove_action
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
       echo "postrm called with unknown argument '$1'" >&2
       exit 1
    ;;
esac

#DEBHELPER#

exit 0
