#!/bin/sh
#
# This file is part of OpenMediaVault-fail2ban.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    OpenMediaVault Plugin Developers <plugins@omv-extras.org>
# @copyright Copyright (c) 2014 OpenMediaVault Plugin Developers
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
        purge)
                SERVICE_XPATH_NAME="fail2ban"
                SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"
        
                if omv_config_exists "${SERVICE_XPATH}"; then
                        omv_config_delete "${SERVICE_XPATH}"
                fi
	;;

	remove)
	;;
	

        upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;

        *)
                echo "postrm called with unknown argument \`$1'" >&2
                exit 1
        ;;
esac

#DEBHELPER#

exit 0
