version: "1.0"
type: component
data:
  name: omv-services-fail2ban-settings-form-page
  type: formPage
  config:
    request:
      service: Fail2ban
      get:
        method: getSettings
      post:
        method: setSettings
    fields:
      - type: checkbox
        name: enable
        label: _("Enable")
        value: false
      - type: textInput
        name: ignoreip
        label: _("Ignore IP")
        value: "127.0.0.1"
        hint: _("Can be an IP address, a CIDR mask or a DNS host, separe with space for multiple ip.")
      - type: numberInput
        name: findtime
        label: _("Find time")
        value: 604800
        validators:
          min: -1
          max: 9999999
          patternType: integer
          required: true
        hint: _("The counter is set to zero if no match is found within 'findtime' seconds. (604800 = 1 week).")
      - type: numberInput
        name: bantime
        label: _("Ban time")
        value: 604800
        validators:
          min: -1
          max: 9999999
          patternType: integer
          required: true
        hint: _("Duration (in seconds) for IP to be banned for. Negative number for 'permanent' ban. (604800 = 1 week).")
      - type: numberInput
        name: maxretry
        label: _("Max retry")
        value: 3
        validators:
          min: 0
          max: 9999
          patternType: integer
          required: true
        hint: _("Number of matches (i.e. value of the counter) which triggers ban action on the IP.")
      - type: textInput
        name: destemail
        label: _("Dest email")
        value: "root@localhost"
        hint: _("An email address to receive ban messages.")
      - type: select
        name: action
        label: _("Action")
        value: "action_mwl"
        store:
          data:
            - ["action_", "action_"]
            - ["action_mw", "action_mw"]
            - ["action_mwl", "action_mwl"]
        hint: _("action_= ban only / action_mw=ban & send an email / action_mwl=ban & send an email with whois report and log lines.")
    buttons:
      - template: submit
      - template: cancel
        execute:
          type: url
          url: "/services/fail2ban"
